### ISSUE TITLE
Attachment Check is only performed when editing the email.

### ISSUE THREAD

**Issue by tlimbacher** [chrisbra/CheckAttach#8]
I have the following problem,
when I am composing an email, i.e opening mutt hitting the m key, enter email address and subject, writing the email (containing the words attached or Anhang in German), saving (:w) and quitting vim (:wq) no attachment check is performed. Finally I am sending the email by pressing the y key.

However, when I am editing the email (e key) after saving and quitting vim (before sending it :)) the check is performed right after I save the email.

Please help.

I am using
- mutt 1.5.23
- vim 7.4
- DWM 6.0-2
  on ArchLinux

**Comment by chrisbra** [comment]
Just for the record, have you :set edit_headers set in your .muttrc?
What filetype is the file, when it does not work? (Check using :set ft?)
Also make sure, an autocommand is created, :au CheckAttach
should show something like this:
``
:au CheckAttach
--- Autokommandos ---
CheckAttach  BufWriteCmd
    <buffer=1>
              :call <SID>CheckAttach()
``

**Comment by tlimbacher** [comment]
edit_headers is set.
The filetype is mail.
:au CheckAttach gives the same output as you mentioned.

**Comment by chrisbra** [comment]
Hm. Did you use `:w!` e.g. the '!' attribute?
Please post the output of this command:

    :redir =>a|:set verbose=20|:w|:set verbose=0|redir end

And after entering, do `:new|:put =a`
and save the dump somewhere.

**Comment by tlimbacher** [comment]
I just use `:w`. When I use `:w!` also the "editing use case" does not work anymore.

[Here](https://drive.google.com/folderview?id=0Bylf16uZJcpRfkRrbFlNX3pJLTJzS2g1OEpwYUFLbXp1VVRvTXBGNkx2Q3Q4VGNiSjByNkk&usp=sharing) are the outputs to the command `:redir =>a|:set verbose=20|:w|:set verbose=0|redir end` in the first and second procedure  (after saving with `:w`) descriped in my ititial post. Please let me know if there is something missing or if I have missunderstood you.

I will try again with a minimal vimrc. Maybe it does not work due to some other settings or plugins...

**Comment by chrisbra** [comment]
Hi tlimbacher!

On Fr, 19 Jun 2015, tlimbacher wrote:

> I just use `:w`. When I use `:w!` also the "editing use case" does not work anymore.

Okay. That is expected. Just to make sure.

> [Here](https://drive.google.com/folderview?id=0Bylf16uZJcpRfkRrbFlNX3pJLTJzS2g1OEpwYUFLbXp1VVRvTXBGNkx2Q3Q4VGNiSjByNkk&usp=sharing) are the outputs to the command `:redir =>a|:set verbose=20|:w|:set verbose=0|redir end` in the first and second procedure  (after saving with `:w`) descriped in my ititial post. Please let me know if there is something missing or if I have missunderstood you.

out1 is the non-working one, right? That looks to me, like the line 31:     
,----
| if search(pat, 'nW') && !<sid>CheckAlreadyAttached(subjline)
`----
Since there is no call to CheckAlreadyAttached(subjline) isn't executed, 
I expect the pattern does not match. Just to make sure, any of the words 
attach,attachment,angehängt,Anhang
are also in the text after the subject line?

If this is true, I think, we might want to step through the function 
using the integrated debugger.

Do :breakadd func *CheckAttach

Then save. step through the function using 'n' for next.
When you are at the above line, do :echo search(pat, 'nW')
This should return > 0 if it finds a match
also do :echo pat so we can see the pattern.
When done, do :c to continue.

You can delete the breakpoint using  :breakdel 1


> I will try again with a minimal vimrc. Maybe it does not work due to some other settings or plugins...

Please for both version, show me the output of :version and perhaps, try 
if :set re=1 makes a difference?

Best,
Christian
-- 
Als Gott die Zeit schuf, hat er genug davon gemacht.
		-- Irisches Sprichwort

**Comment by tlimbacher** [comment]
Hi Christian,
it seems that your script requires an empty line between the header and body of the email. So this works
`From:`
`To:`
`Cc:`
`Bcc:`
`Subject: Test CheckAttach`
`Reply-To:`

 `Hallo,`
 `im Anhang die Dokumente.`

while this

`From:`
`To:`
`Cc:`
`Bcc:`
`Subject: Test CheckAttach`
`Reply-To:`
 `Hallo,`
 `im Anhang die Dokumente.`

does not. Is it a common convention to put an empty line between header and body?
I should have noticed this earlier...

In my .vim/after/ftplugin/mail.vim I have
`call cursor(1,1)`
`call search('^$')`
to set the cursor position to the first line after the header when composing an email.
This is also why it worked when editing the email afterwards (with the e key in mutt). In this case the cursor will again be set to the first line after the header and thus putting an empty line between header and body.

Best,
Thomas

**Comment by chrisbra** [comment]
Hm, I always thought mutt does automatically put an empty line between the header and the start of the body. How did you configure mutt, so that there does not exists an empty line between header and body?

I actually don't think, your .vim/after/ftplugin/mail.vim should have an influence, since the CheckAttach script does put  the cursor temporary to the first line and later restores it, so that it can detect where to put the :Attach header.
Just as a quick check, can you please disable your custom ftplugin/mail.vim configuration and make sure it still doesn't work ;)

**Comment by chrisbra** [comment]
Oh and pleace check, if the latest version works for you. I implemented a work around, that checks, whether the cursor ended up in the last line, before searching for any of the patterns.
